name: deploy.firebase.v1
on:
  workflow_call:
    inputs:
      FIREBASE_PROJECT:
        description: "Firebase project ID"
        required: true
        type: string
      ZMODE:
        description: "Mode name [dev, prod, ...]"
        required: false
        type: string
        default: dev
      FIREBASE_HOSTING_CHANNEL:
        description: "Firebase Hosting channel (e.g., live, preview)"
        required: false
        type: string
        default: "live"
      BUILD_SCRIPT:
        description: "NPM script to build the project"
        required: false
        type: string
        default: "build"
      BUILD_OUTPUT_DIR:
        description: "Build output directory"
        required: false
        type: string
        default: "dist"
      USE_PNPM:
        description: "Use pnpm instead of npm"
        required: false
        type: boolean
        default: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: üì• Checkout code
        uses: actions/checkout@v4

      - name: üîê Obtain GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN=$(npx obtain-github-app-installation-access-token ci ${{secrets.GH_APP_CREDENTIALS_TOKEN}})
          echo "::add-mask::$TOKEN" && echo "::set-output name=token::$TOKEN"

      - name: üîß Configure GitHub authentication
        run: |
          git config --global url."https://oauth2:$GITHUB_TOKEN@github.com/lctech-tw".insteadOf "https://github.com/lctech-tw"
          rm -rf .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "@lctech-tw:registry=https://npm.pkg.github.com/" >> .npmrc
        env:
          GITHUB_TOKEN: ${{steps.githubAppAuth.outputs.token}}

      - name: ‚öôÔ∏è Set up Pnpm
        if: inputs.USE_PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: ‚öôÔ∏è Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: ${{ inputs.USE_PNPM && 'pnpm' || 'npm' }}

      - name: üì¶ Install dependencies
        run: |
          if [ "${{inputs.USE_PNPM}}" == "true" ]; then
            pnpm install --frozen-lockfile
          else
            npm ci
          fi

      - name: üî® Build project
        run: |
          if [ -f ".env.${{inputs.ZMODE}}" ]; then
            cp .env.${{inputs.ZMODE}} .env
          fi
          if [ "${{inputs.USE_PNPM}}" == "true" ]; then
            pnpm run ${{inputs.BUILD_SCRIPT}}
          else
            npm run ${{inputs.BUILD_SCRIPT}}
          fi

      - name: üî• Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{inputs.FIREBASE_PROJECT}}
          channelId: ${{inputs.FIREBASE_HOSTING_CHANNEL}}
          target: ${{inputs.ZMODE}}
