name: Notify

on:
  workflow_call:
    inputs:
      status:
        description: 'A username passed from the caller workflow'
        required: false
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json:  ${{ secrets.GCP_SA_KEY_GITHUB_CI }}
      - name: ⚙️ Initialize Google Cloud SDK
        if: always()
        uses: google-github-actions/setup-gcloud@v0
      - name: Slack Notification
        if: always()
        run: |
          curl -LJO https://raw.githubusercontent.com/lctech-tw/util_scripts/main/notify_slack.sh 
          if [[ '${{ inputs.username }}' == 'failure' ]] ;then
            echo "Run slack on Fail (X)"
            bash ./notify_slack.sh -f
          else
            echo "Run slack on Success (O)"
            bash ./notify_slack.sh -s
          fi